version: 2

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}"

archives:
  - id: provider-archives
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

sboms:
  - id: provider-archive-sboms
    artifacts: archive
    ids:
      - provider-archives
    documents:
      - "${artifact}.spdx.json"
    disable: false

checksum:
  ids:
    - provider-archives
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  draft: true
  use_existing_draft: true
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
